baseURL = "https://brandonrozek.com/"
languageCode = "en-us"
title = "Brandon Rozek"
theme = "pulp"
enableGitInfo = true

[taxonomies]
  series = "series"
  tags = "tags"

[params]
    author = "Brandon Rozek"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = "PhD Student @ RPI studying Automated Reasoning in AI and Linux Enthusiast."
    email = "hello@brandonrozek.com"
    identities = [
        "https://github.com/brandon-rozek",
        "mailto:hello@brandonrozek.com",
        "https://fosstodon.org/@brozek"
    ]

[outputs]
    section = ["JSON", "HTML", "RSS"]
    page = ["HTML", "AMP"]

[[menu.main]]
    identifier = "blog"
    name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fas fa-pen-alt'></i>" #Choose your favorite font from Font Awesome
    url = "/blog/"
    weight = 10

[[menu.main]]
    identifier = "research"
    name = "Research"
    pre = "<i class='fa fa-flask fa-lg'></i>" 
    url = "/research/"
    weight = 20

[[menu.main]]
    identifier = "ta"
    name = "TA"
    pre = "<i class='fa fa-chalkboard-teacher fa-lg'></i>"
    url = "/ta/"
    weight = 30

[[menu.main]]
    identifier = "community"
    name = "Community"
    pre = "<i class='fa fa-user-friends fa-lg'></i>"
    url = "/community/"
    weight = 40



[[menu.profile]]
    identifier = "mastodon"
    name = "Mastodon"
    pre = "<i class='fab fa-mastodon'></i>"
    url = "https://fosstodon.org/@brozek"
    weight = 80

[[menu.profile]]
    identifier = "github"
    name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/brandon-rozek"
    weight = 85

[[menu.profile]]
    identifier = "scholar"
    name = "Google Scholar"
    pre = "<i class='fas fa-graduation-cap'></i>"
    url = "https://scholar.google.com/citations?user=JrgtnwgAAAAJ&hl=en&oi=ao"
    weight = 90


[[menu.profile]]
    identifier = "email"
    name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:hello@brandonrozek.com"
    weight = 95
