baseURL = "https://brandonrozek.com/"
languageCode = "en-us"
title = "Brandon Rozek"
theme = "pulp"
enableGitInfo = true
ignoreErrors = ["error-remote-getjson"]

[taxonomies]
  series = "series"
  tags = "tags"

[author]
    name = "Brandon Rozek"

[params]
    author = "Brandon Rozek"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = "PhD Student @ RPI, Writer of Tidbits, and Linux Enthusiast."
    email = "brozek@brandonrozek.com"
    identities = [
        "https://github.com/brandon-rozek",
        "mailto:brozek@brandonrozek.com",
        "https://fosstodon.org/@brozek"
    ]
    warnPostOlderThanXYears = 2

[services.rss]
  limit = 50

[mediaTypes."application/atom+xml"]
  suffixes = ["atom"]

[mediaTypes."application/activity+json"]
  suffixes = ["ajson"]

[mediaTypes."application/feed+json"]
  suffixes = ["json"]

[outputFormats.atom]
  name = "atom"
  mediaType = "application/atom+xml"
  baseName = "index"
  isPlainText = false
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false

[outputFormats.as2]
  name = "as2"
  mediaType = "application/activity+json"
  baseName = "index"
  isPlainText = false
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false

[outputFormats.json]
  name = "json"
  mediaType = "application/feed+json"
  baseName = "index"
  isPlainText = false
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false


[outputs]
    section = ["json", "html", "rss", "atom", "as2"]
    page = ["html", "amp", "json"]

[[menu.main]]
    identifier = "blog"
    name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fas fa-pen-alt'></i>" #Choose your favorite font from Font Awesome
    url = "/blog/"
    weight = 10

[[menu.main]]
    identifier = "research"
    name = "Research"
    pre = "<i class='fa fa-flask fa-lg'></i>" 
    url = "/research/"
    weight = 20

[[menu.main]]
    identifier = "postroll"
    name = "Postroll"
    pre = "<i class='fas fa-scroll'></i>"
    url = "/postroll"
    weight = 30

[[menu.main]]
    identifier = "community"
    name = "Community"
    pre = "<i class='fa fa-user-friends fa-lg'></i>"
    url = "/community/"
    weight = 40

[[menu.profile]]
    identifier = "email"
    name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:brozek@brandonrozek.com"
    weight = 75

[[menu.profile]]
    identifier = "mastodon"
    name = "Mastodon"
    pre = "<i class='fab fa-mastodon'></i>"
    url = "https://fosstodon.org/@brozek"
    weight = 80

[[menu.profile]]
    identifier = "github"
    name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/brandon-rozek"
    weight = 85
