baseURL = "https://brandonrozek.com/"
languageCode = "en-us"
title = "Brandon Rozek"
author = "Brandon Rozek"
description = "Software Developer, Researcher, and Linux Enthusiast."
theme = "pulp"

[taxonomies]
  series = "series"

[params]
    author = "Brandon Rozek"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        Software Developer, Researcher, and Linux Enthusiast.
    """
    publicationYear = "2019"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML", "RSS"]
    page = ["AMP", "HTML"]

[[menu.main]]
    identifier = "blog"
    name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/blog/"
    weight = 10

[[menu.main]]
    identifier = "community"
    name = "Community"
    pre = "<i class='fa fa-user-friends fa-lg'></i>"
    url = "/community/"
    weight = 30

[[menu.main]]
    identifier = "research"
    name = "Research"
    pre = "<i class='fa fa-flask fa-lg'></i>" 
    url = "/research/"
    weight = 20

[[menu.main]]
    identifier = "Presentations"
    name = "Presentations"
    pre = "<i class='fa fa-comment fa-lg'></i>"
    url = "/presentations/"
    weight = 40

[[menu.main]]
    identifier = "projects"
    name = "Projects (old)"
    pre = "<i class='fa fa-tasks fa-lg'></i>"
    url = "/projects/"
    weight = 70

[[menu.main]]
    identifier = "notes"
    name = "Notes"
    pre = "<i class='fa fa-book-open fa-lg'></i>"
    url = "/notes/"
    weight = 60

[[menu.main]]
    identifier = "ta"
    name = "TA"
    pre = "<i class='fa fa-chalkboard-teacher fa-lg'></i>"    
    url = "/ta/"
    weight = 50


[[menu.main]]
    identifier = "github"
    name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/brandon-rozek"
    weight = 80

[[menu.main]]
    identifier = "email"
    name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:hello@brandonrozek.com"
    weight = 90
