name: Build and Deploy Hugo Website

on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: "21 14 * * *"

defaults:
  run:
    shell: bash

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0

      - name: Git submodule update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Pull down Git LFS files
        run: |
          git lfs fetch
          git lfs checkout

      - name: Setup Hugo
        env:
          HUGO_VERSION: 0.143.1
        run: |
          curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz" --output hugo.tar.gz
          tar -xvzf hugo.tar.gz
          sudo mv hugo /usr/local/bin

      - name: Build Hugo Website
        run: hugo

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_APP_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET: rozek-websites
          S3_PATH: var/www/brandonrozek
        run: ./deploy.sh

      - name: Build Onion Website
        run: |
          rm -rf public/
          hugo --baseURL "http://brozek63j22jry6gof2vszo27vh2ed327bqismqu3somrqu622z73eid.onion/"

      - name: Deploy Onion Website
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_APP_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET: rozek-websites
          S3_PATH: var/www/brandonrozek-onion
        run: ./deploy.sh
